---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
steam_data <- read.csv(url("https://raw.githubusercontent.com/TealKatt/Data-Science-Project/main/data/steam.csv?token=AU22RCLW7XP76J7ZLNMKGU3BWFK7O"))

steam_data
```

```{r}
colnames(steam_data)
```

```{r}
#Lines filter the amount of row in each genre

Action <- steam_data %>%  filter(str_detect(steamspy_tags, "Action"))
Action
nrow(Action)

FPS <- steam_data %>%  filter(str_detect(steamspy_tags, "FPS"))
FPS
nrow(FPS)

Shooter <- steam_data %>%  filter(str_detect(steamspy_tags, "Shooter"))
Shooter
nrow(Shooter)

Sci_fi <- steam_data %>%  filter(str_detect(steamspy_tags, "Sci-fi"))
Sci_fi
nrow(Sci_fi) 

Puzzle <- steam_data %>%  filter(str_detect(steamspy_tags, "Puzzle"))
Puzzle
nrow(Puzzle)

Indie <- steam_data %>%  filter(str_detect(steamspy_tags, "Indie"))
Indie
nrow(Indie)

Strategy <- steam_data %>%  filter(str_detect(steamspy_tags, "Strategy"))
Strategy
nrow(Strategy)

Racing <- steam_data %>%  filter(str_detect(steamspy_tags, "Racing"))
Racing
nrow(Racing)

RPG <- steam_data %>%  filter(str_detect(steamspy_tags, "RPG"))
RPG
nrow(RPG)

Casual <- steam_data %>%  filter(str_detect(steamspy_tags, "Casual"))
Casual
nrow(Casual)

Horror <- steam_data %>%  filter(str_detect(steamspy_tags, "Horror"))
Horror
nrow(Horror)

Simulation <- steam_data %>%  filter(str_detect(steamspy_tags, "Simulation"))
Simulation
nrow(Simulation)
```

```{r}
 #Genres

Top_Games <- data.frame (Genres = c("Action", "FPS", "Shooter", "Sci-fi", "Puzzle", "Indie", "Strategy", "Racing", "RPG", "Casual", "Horror", "Simulation"), Amount = c(10344,405,227,157,1167,16232,4180,765,2863,8205,566,3284))


#ggplot(Top_Games, aes(x = Genres, y = Ammount_of_games)) + geom_col(fill = "black") 
ggplot(Top_Games, aes(x = Genres, y = Amount, fill = Genres,)) + geom_bar(stat = "identity", width = 0.5) + coord_flip()

```




